name = "DCDC"
uuid = "e3561b90-e7a2-11e8-22a6-450fa8459ba9"
authors = ["Jasmine Hao <haojasmine@gmail.com>"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
